"""initial imgration

Revision ID: 021e131966ad
Revises: c8afcb234292
Create Date: 2018-05-17 22:20:39.140816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021e131966ad'
down_revision = 'c8afcb234292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('users', 'location')
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
