"""initial migration

Revision ID: 1c5e5ee741d6
Revises: d9675f358155
Create Date: 2018-05-14 23:33:05.715545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5e5ee741d6'
down_revision = 'd9675f358155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_users_old_20180514')
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    op.create_table('_users_old_20180514',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=200), nullable=True),
    sa.Column('psd', sa.VARCHAR(length=40), nullable=True),
    sa.Column('mail', sa.VARCHAR(length=200), nullable=True),
    sa.Column('recdate', sa.DATETIME(), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.Column('phonenum', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
