"""initial migration

Revision ID: 590fd734f2d4
Revises: b3c0aafd9123
Create Date: 2018-05-19 22:35:37.263067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590fd734f2d4'
down_revision = 'b3c0aafd9123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestap', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_timestap'), 'posts', ['timestap'], unique=False)
    op.add_column('users', sa.Column('user_pic_40', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_pic_40')
    op.drop_index(op.f('ix_posts_timestap'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
