"""initial migration

Revision ID: 9148388dc928
Revises: ac8ea6456972
Create Date: 2018-05-12 18:17:13.294191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9148388dc928'
down_revision = 'ac8ea6456972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_unique_constraint(None, 'users', ['mail'])
    # ### end Alembic commands ###
	pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
	pass
