"""initial migration

Revision ID: b27ef17b311d
Revises: 9148388dc928
Create Date: 2018-05-12 18:19:02.422790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27ef17b311d'
down_revision = '9148388dc928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass#op.create_unique_constraint(None, 'users', ['mail'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass#op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
