"""initial migration

Revision ID: b3c0aafd9123
Revises: e40fe2bad5f6
Create Date: 2018-05-19 18:36:21.488039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c0aafd9123'
down_revision = 'e40fe2bad5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_pic_small', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_pic_small')
    # ### end Alembic commands ###
