# Generated by Django 2.0.5 on 2018-05-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebDemo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='recdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
