"""initial migration

Revision ID: 3f2325e8c285
Revises: 721b840c5da3
Create Date: 2018-05-11 23:12:10.328111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2325e8c285'
down_revision = '721b840c5da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_users_old_20180511_1')
    op.drop_table('_users_old_20180511')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_users_old_20180511',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=200), nullable=True),
    sa.Column('recdate', sa.DATETIME(), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.Column('mail', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_users_old_20180511_1',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=200), nullable=True),
    sa.Column('recdate', sa.DATETIME(), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.Column('mail', sa.VARCHAR(length=200), nullable=True),
    sa.Column('psd', sa.VARCHAR(length=40), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
